### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by jiacai2050** [Gooreplacer/GooreplacerCn#1]
感谢作者的辛苦工作，但是有以下几点疑问：
- 为什么要单独开个仓库来做汉化？ https://github.com/jiacai2050/gooreplacer/issues/50 这个是 i18n 的 issue，可以直接提交 PR，不需要懂 cljs 代码
- https://github.com/Gooreplacer/gooreplacer 这个仓库的意义感觉不是很大，我也想过，把 gooreplacer 做成一个开发的插件，用户可以添加自定义 js 代码，而不仅仅是通过正则去匹配，就像[油猴脚本](https://greasyfork.org/zh-CN)，但是由于工作量有些大，且没有精力投入，就一直没有进行，如果你又兴趣，可以简单[学习下 cljs](https://github.com/magomimmo/modern-cljs)，来完善这个插件，能完成这个功能后，可以在考虑搭建社区的工作。

最后再次感谢作者的辛苦工作。🍺

**Comment by yakeing** [comment]
1.首先不要把国人想个是高手，简单就是好用的，默认是英文，有个可以选择语言按钮正好了。
2. 新版Chrome 浏览器不可以直接本地安装 crx 文件，应用商店没有梯子是打不开的，有梯子还会用插件吗？
不是我想分流你的插件，插件是好的但十有八九国人真的不会用。

**Comment by yakeing** [comment]
当然如果这个组织存在不合理或侵犯的的权限我随时可以把它删除，给你带来困扰感到十分抱歉。

**Comment by jiacai2050** [comment]
> 1.首先不要把国人想个是高手，简单就是好用的，默认是英文，有个可以选择语言按钮正好了。

解决思路不应该是提个 PR，解决 https://github.com/jiacai2050/gooreplacer/issues/50 嘛？另开一个仓库，怎么和主仓库同步？

> 不是我想分流你的插件，插件是好的但十有八九国人真的不会用。

我上面也说了，现在还远不到建社区的时候，根本就没有扩展性。

感觉你要是感兴趣，可以先把这两个特性完善，再考虑建社区。

**Comment by jiacai2050** [comment]
https://github.com/jiacai2050/gooreplacer/issues/50 周末把 i18n 加上了，目前有英文 + 中文两种，可以使用看看。会根据浏览器 locale 自动选择。
